package com.entertainment.musicpage.dao.models;
// default package
// Generated Jun 6, 2013 11:46:43 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlbumsongId generated by hbm2java
 */
@Embeddable
public class AlbumsongId implements java.io.Serializable {

	private int idAlbum;
	private int idSong;

	public AlbumsongId() {
	}

	public AlbumsongId(int idAlbum, int idSong) {
		this.idAlbum = idAlbum;
		this.idSong = idSong;
	}

	@Column(name = "idAlbum", nullable = false)
	public int getIdAlbum() {
		return this.idAlbum;
	}

	public void setIdAlbum(int idAlbum) {
		this.idAlbum = idAlbum;
	}

	@Column(name = "idSong", nullable = false)
	public int getIdSong() {
		return this.idSong;
	}

	public void setIdSong(int idSong) {
		this.idSong = idSong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlbumsongId))
			return false;
		AlbumsongId castOther = (AlbumsongId) other;

		return (this.getIdAlbum() == castOther.getIdAlbum())
				&& (this.getIdSong() == castOther.getIdSong());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAlbum();
		result = 37 * result + this.getIdSong();
		return result;
	}

}
