package com.entertainment.musicpage.dao.models;
// default package
// Generated May 28, 2013 11:52:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "musicpage")
public class Album implements java.io.Serializable {

	private AlbumId id;
	private String title;
	private String source;
	private String sourceType;
	private String description;
	private Date createdTime;
	private Date modifyTime;

	public Album() {
	}

	public Album(AlbumId id, String title, String source, String sourceType,
			Date createdTime, Date modifyTime) {
		this.id = id;
		this.title = title;
		this.source = source;
		this.sourceType = sourceType;
		this.createdTime = createdTime;
		this.modifyTime = modifyTime;
	}

	public Album(AlbumId id, String title, String source, String sourceType,
			String description, Date createdTime, Date modifyTime) {
		this.id = id;
		this.title = title;
		this.source = source;
		this.sourceType = sourceType;
		this.description = description;
		this.createdTime = createdTime;
		this.modifyTime = modifyTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "idSong", column = @Column(name = "idSong", nullable = false)) })
	public AlbumId getId() {
		return this.id;
	}

	public void setId(AlbumId id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 555)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "source", nullable = false, length = 555)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "sourceType", nullable = false, length = 555)
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "description", length = 5555)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdTime", nullable = false, length = 10)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifyTime", nullable = false, length = 10)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
