package com.entertainment.musicpage.dao.models;
// default package
// Generated May 28, 2013 11:52:58 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlbumId generated by hbm2java
 */
@Embeddable
public class AlbumId implements java.io.Serializable {

	private int id;
	private int idSong;

	public AlbumId() {
	}

	public AlbumId(int id, int idSong) {
		this.id = id;
		this.idSong = idSong;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "idSong", nullable = false)
	public int getIdSong() {
		return this.idSong;
	}

	public void setIdSong(int idSong) {
		this.idSong = idSong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlbumId))
			return false;
		AlbumId castOther = (AlbumId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdSong() == castOther.getIdSong());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdSong();
		return result;
	}

}
