/***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 package com.entertainment.musicpage.dao.customdaosupport;
 
 import java.io.Serializable;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
 
 
 public abstract class CustomDAOSupport implements Serializable {
 
 private static final long serialVersionUID = 1L;
 private static Session daoManager;
// = new org.hibernate.cfg.Configuration()
//	.configure("hibernate.cfg.xml").buildSessionFactory().openSession();
 private static SessionFactory sessFac = new org.hibernate.cfg.Configuration()
	.configure("hibernate.cfg.xml").buildSessionFactory();

 public void anyMethodName(SessionFactory sessionFactory){
 	CustomDAOSupport.daoManager = sessionFactory.getCurrentSession();
 	daoManager.beginTransaction();
 }
 
 public static Session getDAOManager() {
	if(daoManager == null){
			daoManager = sessFac.openSession();
	} 
 	return daoManager;
 }
 
 }