
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.entertainment.musicpage.dao.dao;
 
 
 
 import java.io.Serializable;
 import java.util.List;
 import com.entertainment.musicpage.dao.models.Album;
 import java.lang.Integer;
 import java.lang.String;
 import java.util.Date;
 
 
 /***************************************************
 *DAO interface of album table.
 *Generated on Sat Jun 01 01:50:25 ICT 2013
 ***************************************************/
 
 
 public interface AlbumDAO extends Serializable {
 
 /**
 * @return Album
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> findAll();
 
 /**
 * Inserts Album
 * @param: Album
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public void save(Album arg0);
 
 /**
 * Updates Album
 * @param: Album
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public void update(Album arg0);
 
 /**
 * Removes Album
 * @param: Album
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public void delete(Album arg0);
 
 /**
 * @return Album
 * @param: java.lang.Integer Id
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumById(Integer id);

/**
 * @return Album
 * @param: java.lang.Integer id
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumById(Integer id, int startPosition, int maxResult);
 
 /**
 * @return Album
 * @param: java.lang.String Title
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByTitle(String title);

/**
 * @return Album
 * @param: java.lang.String title
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByTitle(String title, int startPosition, int maxResult);
 
 /**
 * @return Album
 * @param: java.lang.String Source
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySource(String source);

/**
 * @return Album
 * @param: java.lang.String source
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySource(String source, int startPosition, int maxResult);
 
 /**
 * @return Album
 * @param: java.lang.String Sourcetype
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySourcetype(String sourcetype);

/**
 * @return Album
 * @param: java.lang.String sourcetype
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySourcetype(String sourcetype, int startPosition, int maxResult);
 
 /**
 * @return Album
 * @param: java.lang.String Description
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByDescription(String description);

/**
 * @return Album
 * @param: java.lang.String description
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByDescription(String description, int startPosition, int maxResult);
 
 /**
 * @return Album
 * @param: java.util.Date Createdtime
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByCreatedtime(Date createdtime);

/**
 * @return Album
 * @param: java.util.Date createdtime
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByCreatedtime(Date createdtime, int startPosition, int maxResult);
 
 /**
 * @return Album
 * @param: java.util.Date Modifytime
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByModifytime(Date modifytime);

/**
 * @return Album
 * @param: java.util.Date modifytime
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByModifytime(Date modifytime, int startPosition, int maxResult);
 
 
 
 
 }