
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.entertainment.musicpage.dao.dao;
 
 
 
 import java.io.Serializable;
 import java.util.List;
 import com.entertainment.musicpage.dao.models.Albumsong;
 import java.lang.Integer;
 
 
 /***************************************************
 *DAO interface of albumsong table.
 *Generated on Sat Jun 01 01:50:25 ICT 2013
 ***************************************************/
 
 
 public interface AlbumsongDAO extends Serializable {
 
 /**
 * @return Albumsong
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Albumsong
 */
	public List<Albumsong> findAll();
 
 /**
 * Inserts Albumsong
 * @param: Albumsong
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Albumsong
 */
	public void save(Albumsong arg0);
 
 /**
 * Updates Albumsong
 * @param: Albumsong
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Albumsong
 */
	public void update(Albumsong arg0);
 
 /**
 * Removes Albumsong
 * @param: Albumsong
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Albumsong
 */
	public void delete(Albumsong arg0);
 
 /**
 * @return Albumsong
 * @param: java.lang.Integer Idalbum
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Albumsong
 */
	public List<Albumsong> getAlbumsongByIdalbum(Integer idalbum);

/**
 * @return Albumsong
 * @param: java.lang.Integer idalbum
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Albumsong
 */
	public List<Albumsong> getAlbumsongByIdalbum(Integer idalbum, int startPosition, int maxResult);
 
 /**
 * @return Albumsong
 * @param: java.lang.Integer Idsong
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Albumsong
 */
	public List<Albumsong> getAlbumsongByIdsong(Integer idsong);

/**
 * @return Albumsong
 * @param: java.lang.Integer idsong
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Sat Jun 01 01:50:25 ICT 2013
 * @See Albumsong
 */
	public List<Albumsong> getAlbumsongByIdsong(Integer idsong, int startPosition, int maxResult);
 
 
 
 
 }