
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.entertainment.musicpage.dao.bo.impl;
 
 
 import com.entertainment.musicpage.dao.bo.AlbumBO;
 import com.entertainment.musicpage.dao.dao.impl.AlbumDAOImpl;
 
 import java.io.Serializable;
 import java.util.List;
 import com.entertainment.musicpage.dao.models.Album;
 import java.lang.Integer;
 import java.lang.String;
 import java.util.Date;
 
 
 /***************************************************
 *BO interface of album table.
 *Generated on Tue May 28 23:59:52 ICT 2013
 ***************************************************/
 
 
 public class AlbumBOImpl implements AlbumBO {
 
 
 
 		 AlbumDAOImpl albumDAO;
 
 /**
 * @return Album
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> findAll(){
		return albumDAO.findAll();

	}
 
 /**
 * Inserts Album
 * @param: Album
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public void save(Album arg0){
		albumDAO.save(arg0);

	}
 
 /**
 * Updates Album
 * @param: Album
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public void update(Album arg0){
		albumDAO.update(arg0);

	}
 
 /**
 * Removes Album
 * @param: Album
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public void delete(Album arg0){
		albumDAO.delete(arg0);

	}
 
 /**
 * @return Album
 * @param: java.lang.Integer Id
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumById(Integer id){
		return albumDAO.getAlbumById(id);

	}

/**
 * @return Album
 * @param: java.lang.Integer id
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumById(Integer id, int startPosition, int maxResult){
		return albumDAO.getAlbumById(id, startPosition, maxResult);

	}
 
 /**
 * @return Album
 * @param: java.lang.Integer Idsong
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByIdsong(Integer idsong){
		return albumDAO.getAlbumByIdsong(idsong);

	}

/**
 * @return Album
 * @param: java.lang.Integer idsong
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByIdsong(Integer idsong, int startPosition, int maxResult){
		return albumDAO.getAlbumByIdsong(idsong, startPosition, maxResult);

	}
 
 /**
 * @return Album
 * @param: java.lang.String Title
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByTitle(String title){
		return albumDAO.getAlbumByTitle(title);

	}

/**
 * @return Album
 * @param: java.lang.String title
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByTitle(String title, int startPosition, int maxResult){
		return albumDAO.getAlbumByTitle(title, startPosition, maxResult);

	}
 
 /**
 * @return Album
 * @param: java.lang.String Source
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySource(String source){
		return albumDAO.getAlbumBySource(source);

	}

/**
 * @return Album
 * @param: java.lang.String source
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySource(String source, int startPosition, int maxResult){
		return albumDAO.getAlbumBySource(source, startPosition, maxResult);

	}
 
 /**
 * @return Album
 * @param: java.lang.String Sourcetype
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySourcetype(String sourcetype){
		return albumDAO.getAlbumBySourcetype(sourcetype);

	}

/**
 * @return Album
 * @param: java.lang.String sourcetype
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySourcetype(String sourcetype, int startPosition, int maxResult){
		return albumDAO.getAlbumBySourcetype(sourcetype, startPosition, maxResult);

	}
 
 /**
 * @return Album
 * @param: java.lang.String Description
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByDescription(String description){
		return albumDAO.getAlbumByDescription(description);

	}

/**
 * @return Album
 * @param: java.lang.String description
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByDescription(String description, int startPosition, int maxResult){
		return albumDAO.getAlbumByDescription(description, startPosition, maxResult);

	}
 
 /**
 * @return Album
 * @param: java.util.Date Createdtime
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByCreatedtime(Date createdtime){
		return albumDAO.getAlbumByCreatedtime(createdtime);

	}

/**
 * @return Album
 * @param: java.util.Date createdtime
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByCreatedtime(Date createdtime, int startPosition, int maxResult){
		return albumDAO.getAlbumByCreatedtime(createdtime, startPosition, maxResult);

	}
 
 /**
 * @return Album
 * @param: java.util.Date Modifytime
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByModifytime(Date modifytime){
		return albumDAO.getAlbumByModifytime(modifytime);

	}

/**
 * @return Album
 * @param: java.util.Date modifytime
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByModifytime(Date modifytime, int startPosition, int maxResult){
		return albumDAO.getAlbumByModifytime(modifytime, startPosition, maxResult);

	}
 
 
 
 
 }