
 /***************************************************
 * Generated by DAOGenerator http://daogenerator.u-db.com
 * http://daogenerator.u-db.com email: buraksrc@gmail.com
 ***************************************************/
 
 
 package com.entertainment.musicpage.dao.dao.impl;
 
 
 import com.entertainment.musicpage.dao.dao.AlbumDAO;
 
 
 
 import java.io.Serializable;
 import com.entertainment.musicpage.dao.customdaosupport.CustomDAOSupport;
 import org.hibernate.Query;
 import java.util.List;
 import com.entertainment.musicpage.dao.models.Album;
 import java.lang.Integer;
 import java.lang.String;
 import java.util.Date;
 
 
 /***************************************************
 *DAO class of album table.
 *Generated on Tue May 28 23:59:52 ICT 2013
 ***************************************************/
 
 
 public class AlbumDAOImpl extends CustomDAOSupport implements Serializable, AlbumDAO {
 
 /**
 * @return Album
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> findAll(){

		Query query = getDAOManager().createQuery(" select t from Album t");

		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * Inserts Album
 * @param: Album
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public void save(Album arg0){

		getDAOManager().persist(arg0);

	}
 
 /**
 * Updates Album
 * @param: Album
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public void update(Album arg0){

		getDAOManager().merge(arg0);

	}
 
 /**
 * Removes Album
 * @param: Album
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public void delete(Album arg0){

		getDAOManager().delete(arg0);

	}
 
 /**
 * @return Album
 * @param: java.lang.Integer Id
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumById(Integer id){

		Query query = getDAOManager().createQuery(" select t from Album t where t.id = ?1 ");

		query.setParameter(1, id);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Album
 * @param: java.lang.Integer id
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumById(Integer id, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Album t where t.id = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, id);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Album
 * @param: java.lang.Integer Idsong
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByIdsong(Integer idsong){

		Query query = getDAOManager().createQuery(" select t from Album t where t.idsong = ?1 ");

		query.setParameter(1, idsong);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Album
 * @param: java.lang.Integer idsong
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByIdsong(Integer idsong, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Album t where t.idsong = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, idsong);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Album
 * @param: java.lang.String Title
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByTitle(String title){

		Query query = getDAOManager().createQuery(" select t from Album t where t.title = ?1 ");

		query.setParameter(1, title);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Album
 * @param: java.lang.String title
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByTitle(String title, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Album t where t.title = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, title);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Album
 * @param: java.lang.String Source
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySource(String source){

		Query query = getDAOManager().createQuery(" select t from Album t where t.source = ?1 ");

		query.setParameter(1, source);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Album
 * @param: java.lang.String source
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySource(String source, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Album t where t.source = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, source);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Album
 * @param: java.lang.String Sourcetype
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySourcetype(String sourcetype){

		Query query = getDAOManager().createQuery(" select t from Album t where t.sourcetype = ?1 ");

		query.setParameter(1, sourcetype);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Album
 * @param: java.lang.String sourcetype
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumBySourcetype(String sourcetype, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Album t where t.sourcetype = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, sourcetype);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Album
 * @param: java.lang.String Description
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByDescription(String description){

		Query query = getDAOManager().createQuery(" select t from Album t where t.description = ?1 ");

		query.setParameter(1, description);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Album
 * @param: java.lang.String description
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByDescription(String description, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Album t where t.description = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, description);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Album
 * @param: java.util.Date Createdtime
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByCreatedtime(Date createdtime){

		Query query = getDAOManager().createQuery(" select t from Album t where t.createdtime = ?1 ");

		query.setParameter(1, createdtime);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Album
 * @param: java.util.Date createdtime
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByCreatedtime(Date createdtime, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Album t where t.createdtime = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, createdtime);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 /**
 * @return Album
 * @param: java.util.Date Modifytime
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByModifytime(Date modifytime){

		Query query = getDAOManager().createQuery(" select t from Album t where t.modifytime = ?1 ");

		query.setParameter(1, modifytime);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}

/**
 * @return Album
 * @param: java.util.Date modifytime
 * @param: int startposition
 * @param: int maxresults
 * Generated on: Tue May 28 23:59:52 ICT 2013
 * @See Album
 */
	public List<Album> getAlbumByModifytime(Date modifytime, int startPosition, int maxResult){

		Query query = getDAOManager().createQuery(" select t from Album t where t.modifytime = ?1 ");

		if(startPosition > 0 && startPosition < maxResult){
			query.setMaxResults(maxResult);
			query.setFirstResult(startPosition);
		}

			query.setParameter(1, modifytime);


		List<Album> results = query.list();

		if (results !=null && results.size() > 0) {
			return results;
		}

		return null;
	}
 
 
 
 
 }