package com.entertainment.musicpage.dao;
// default package
// Generated May 27, 2013 7:20:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "musicpage")
public class Album implements java.io.Serializable {

	private AlbumId id;
	private String title;
	private String source;
	private String sourceType;
	private String description;

	public Album() {
	}

	public Album(AlbumId id, String title, String source, String sourceType) {
		this.id = id;
		this.title = title;
		this.source = source;
		this.sourceType = sourceType;
	}

	public Album(AlbumId id, String title, String source, String sourceType,
			String description) {
		this.id = id;
		this.title = title;
		this.source = source;
		this.sourceType = sourceType;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "idSong", column = @Column(name = "idSong", nullable = false)) })
	public AlbumId getId() {
		return this.id;
	}

	public void setId(AlbumId id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 555)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "source", nullable = false, length = 555)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "sourceType", nullable = false, length = 555)
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "description", length = 5555)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
