package com.entertainment.musicpage.dao;
// default package
// Generated May 27, 2013 7:20:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Song generated by hbm2java
 */
@Entity
@Table(name = "song", catalog = "musicpage")
public class Song implements java.io.Serializable {

	private Integer id;
	private String title;
	private String source;
	private String sourceType;
	private String description;

	public Song() {
	}

	public Song(String title, String source, String sourceType) {
		this.title = title;
		this.source = source;
		this.sourceType = sourceType;
	}

	public Song(String title, String source, String sourceType,
			String description) {
		this.title = title;
		this.source = source;
		this.sourceType = sourceType;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 555)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "source", nullable = false, length = 555)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "sourceType", nullable = false, length = 555)
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "description", length = 5555)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
