package com.entertainment.musicpage.dao.models;
// default package
// Generated Jun 1, 2013 1:34:35 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "musicpage")
public class Album implements java.io.Serializable {

	private int id;
	private String title;
	private String source;
	private String sourceType;
	private String description;
	private Date createdTime;
	private Date modifyTime;

	public Album() {
	}

	public Album(int id, String title, String source, String sourceType,
			Date createdTime, Date modifyTime) {
		this.id = id;
		this.title = title;
		this.source = source;
		this.sourceType = sourceType;
		this.createdTime = createdTime;
		this.modifyTime = modifyTime;
	}

	public Album(int id, String title, String source, String sourceType,
			String description, Date createdTime, Date modifyTime) {
		this.id = id;
		this.title = title;
		this.source = source;
		this.sourceType = sourceType;
		this.description = description;
		this.createdTime = createdTime;
		this.modifyTime = modifyTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false, length = 555)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "source", nullable = false, length = 555)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "sourceType", nullable = false, length = 555)
	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	@Column(name = "description", length = 5555)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdTime", nullable = false, length = 10)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modifyTime", nullable = false, length = 10)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
