package com.entertainment.musicpage.dao.models;
// default package
// Generated Jun 1, 2013 1:34:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Albumsong generated by hbm2java
 */
@Entity
@Table(name = "albumsong", catalog = "musicpage")
public class Albumsong implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AlbumsongId id;

	public Albumsong() {
	}

	public Albumsong(AlbumsongId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idAlbum", column = @Column(name = "idAlbum", nullable = false)),
			@AttributeOverride(name = "idSong", column = @Column(name = "idSong", nullable = false)) })
	public AlbumsongId getId() {
		return this.id;
	}

	public void setId(AlbumsongId id) {
		this.id = id;
	}

}
